### ISSUE TITLE
Move this condition to the stage

### ISSUE THREAD

**Issue by mkaszub** [proofdock/chaos-azure#22]
Currently this condition is evaluated after stage is started but it should be before. In pipeline view it looks like it was executed as first job was started. Moving it to stage condition should solve the issue

Move this condition one level up to the stage (instead of job)
https://github.com/proofdock/chaos-azure/blob/449e01f00705280d93b3b104101c0a1df88f889d/.pipelines/deploy.latest.yml#L31

**Comment by bugraderre** [comment]
Sounds good
